package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/KhalidEchchahid/go-jpm/internal/core"
	"github.com/KhalidEchchahid/go-jpm/internal/engine/native"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// deps_lock.go implements "jpm deps lock" which generates a lockfile
// for reproducible builds.

var depsLockCmd = &cobra.Command{
	Use:   "lock",
	Short: "Generate dependency lockfile",
	Long: `Generate or update jpm.lock for reproducible builds.

The lockfile records the exact versions of all direct and transitive dependencies,
along with their SHA-256 checksums. This ensures that builds are reproducible
across different machines and time.`,
	Args: cobra.NoArgs,
	RunE: runDepsLock,
}

func init() {
	depsCmd.AddCommand(depsLockCmd)

	depsLockCmd.Flags().String("path", ".", "Project directory containing jpm.yaml")
	depsLockCmd.Flags().Bool("verify", false, "Verify existing lockfile instead of generating")
}

// LockFile represents the jpm.lock file structure
type LockFile struct {
	Version     string          `yaml:"version"`
	GeneratedAt string          `yaml:"generated_at"`
	Checksum    string          `yaml:"checksum"` // Hash of jpm.yaml dependencies
	Packages    []LockedPackage `yaml:"packages"`
}

// LockedPackage represents a locked dependency
type LockedPackage struct {
	GroupID    string `yaml:"group_id"`
	ArtifactID string `yaml:"artifact_id"`
	Version    string `yaml:"version"`
	Scope      string `yaml:"scope,omitempty"`
	Sha256     string `yaml:"sha256"`
	Direct     bool   `yaml:"direct"` // true if direct dependency, false if transitive
}

func runDepsLock(cmd *cobra.Command, args []string) error {
	projectPath, _ := cmd.Flags().GetString("path")
	projectPath = strings.TrimSpace(projectPath)
	if projectPath == "" {
		projectPath = "."
	}
	projectPath, err := filepath.Abs(projectPath)
	if err != nil {
		return fmt.Errorf("failed to resolve project path: %w", err)
	}

	verify, _ := cmd.Flags().GetBool("verify")

	// Load manifest
	manifestPath := filepath.Join(projectPath, "jpm.yaml")
	manifestData, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("no jpm.yaml found in %s (run 'jpm init')", projectPath)
	}

	var manifest core.Manifest
	if err := yaml.Unmarshal(manifestData, &manifest); err != nil {
		return fmt.Errorf("failed to parse jpm.yaml: %w", err)
	}

	lockPath := filepath.Join(projectPath, "jpm.lock")

	if verify {
		return verifyLockFile(lockPath, manifest)
	}

	return generateLockFile(projectPath, lockPath, manifest)
}

func generateLockFile(projectPath, lockPath string, manifest core.Manifest) error {
	fmt.Println(headerStyle("→ generating lockfile:"))

	if len(manifest.Dependencies) == 0 {
		fmt.Println("  no dependencies to lock")
		return nil
	}

	// Calculate checksum of dependencies section
	depsChecksum := calculateDepsChecksum(manifest.Dependencies)

	// Resolve all dependencies with transitives
	cacheDir := filepath.Join(projectPath, ".jpm", "cache")
	cache := native.NewCache(cacheDir)
	downloader := native.NewDownloader("", cache)
	resolver := native.NewResolver(downloader, cache)

	coreDeps := make([]core.Dependency, len(manifest.Dependencies))
	directDeps := make(map[string]bool)
	for i, d := range manifest.Dependencies {
		coreDeps[i] = core.Dependency{
			GroupID:    d.GroupID,
			ArtifactID: d.ArtifactID,
			Version:    d.Version,
			Scope:      d.Scope,
		}
		directDeps[d.GroupID+":"+d.ArtifactID] = true
	}

	fmt.Printf("  resolving %d direct dependencies...\n", len(coreDeps))
	resolved, err := resolver.Resolve(coreDeps)
	if err != nil {
		return fmt.Errorf("failed to resolve dependencies: %w", err)
	}

	fmt.Printf("  resolved %d total packages (including transitives)\n", len(resolved))

	// Build lock file
	lockFile := LockFile{
		Version:     "1",
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Checksum:    depsChecksum,
		Packages:    make([]LockedPackage, 0, len(resolved)),
	}

	fmt.Println("  calculating checksums...")
	for _, dep := range resolved {
		sha256sum := ""
		if dep.LocalPath != "" {
			sha256sum, _ = calculateFileSha256(dep.LocalPath)
		}

		key := dep.Artifact.GroupID + ":" + dep.Artifact.ArtifactID
		lockFile.Packages = append(lockFile.Packages, LockedPackage{
			GroupID:    dep.Artifact.GroupID,
			ArtifactID: dep.Artifact.ArtifactID,
			Version:    dep.Artifact.Version,
			Scope:      dep.Scope,
			Sha256:     sha256sum,
			Direct:     directDeps[key],
		})
	}

	// Write lock file
	lockData, err := yaml.Marshal(&lockFile)
	if err != nil {
		return fmt.Errorf("failed to serialize lockfile: %w", err)
	}

	// Add header comment
	header := "# JPM Lockfile - DO NOT EDIT\n# This file is auto-generated by 'jpm deps lock'\n# Run 'jpm deps lock --verify' to validate\n\n"
	lockData = append([]byte(header), lockData...)

	if err := os.WriteFile(lockPath, lockData, 0644); err != nil {
		return fmt.Errorf("failed to write lockfile: %w", err)
	}

	fmt.Println("\n  " + headerStyle("✓ lockfile generated:") + " jpm.lock")
	fmt.Printf("  %d packages locked\n", len(lockFile.Packages))

	return nil
}

func verifyLockFile(lockPath string, manifest core.Manifest) error {
	fmt.Println(headerStyle("→ verifying lockfile:"))

	data, err := os.ReadFile(lockPath)
	if err != nil {
		return fmt.Errorf("no jpm.lock found (run 'jpm deps lock' to generate)")
	}

	var lockFile LockFile
	if err := yaml.Unmarshal(data, &lockFile); err != nil {
		return fmt.Errorf("failed to parse jpm.lock: %w", err)
	}

	// Check if dependencies have changed
	currentChecksum := calculateDepsChecksum(manifest.Dependencies)
	if currentChecksum != lockFile.Checksum {
		fmt.Println("  " + warningTextStyle("✗ jpm.yaml dependencies have changed"))
		fmt.Println("  run 'jpm deps lock' to regenerate the lockfile")
		return fmt.Errorf("lockfile out of sync")
	}

	fmt.Println("  ✓ dependency checksums match")
	fmt.Printf("  ✓ %d packages verified\n", len(lockFile.Packages))
	fmt.Println("\n  " + headerStyle("✓ lockfile is valid"))

	return nil
}

func calculateDepsChecksum(deps []core.Dependency) string {
	var sb strings.Builder
	for _, d := range deps {
		sb.WriteString(fmt.Sprintf("%s:%s:%s:%s\n", d.GroupID, d.ArtifactID, d.Version, d.Scope))
	}
	hash := sha256.Sum256([]byte(sb.String()))
	return hex.EncodeToString(hash[:])
}

func calculateFileSha256(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:]), nil
}
