package init

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ReadmeGenerator creates or updates a README.md file with project quickstart.
type ReadmeGenerator struct {
	projectRoot string
	projectName string
	javaVersion string
	mainClass   string
}

// NewReadmeGenerator creates a new README generator.
func NewReadmeGenerator(projectRoot, projectName, javaVersion, mainClass string) *ReadmeGenerator {
	return &ReadmeGenerator{
		projectRoot: projectRoot,
		projectName: projectName,
		javaVersion: javaVersion,
		mainClass:   mainClass,
	}
}

// readmeTemplate is the README.md template with placeholders.
const readmeTemplate = `# {{project_name}}

A Java project managed by JPM.

## Quickstart

- **Build**: ` + "`jpm build`" + `
- **Run**: ` + "`jpm run`" + `
- **Add dependencies**: ` + "`jpm deps add group:artifact@version`" + `

## Project Structure

- ` + "`src/`" + ` — Your Java source files
- ` + "`.jpm/`" + ` — JPM internals (build artifacts, cache, logs, outputs)
- ` + "`jpm.yaml`" + ` — Project manifest and configuration
- ` + "`jpm.lock.yaml`" + ` — Locked dependency versions (reproducibility)

## Running Your Project

If a main class is not set in ` + "`jpm.yaml`" + `, JPM will prompt you or attempt to auto-detect it.

Configure in ` + "`jpm.yaml`" + `:
` + "```yaml" + `
app:
  main_class: com.example.Main
` + "```" + `

Then run: ` + "`jpm run`" + `

## Managing Dependencies

Add a dependency:
` + "```bash" + `
jpm deps add org.slf4j:slf4j-api@2.0.16
` + "```" + `

View dependency tree:
` + "```bash" + `
jpm deps tree
` + "```" + `

## Troubleshooting

- **Java not found**: Install JDK 21 using SDKMAN (` + "`curl https://get.sdkman.io | bash && sdk install java 21.0.1-tem`" + `), Homebrew (` + "`brew install temurin@21`" + `), or manually, then set ` + "`JAVA_HOME`" + `.
- **Symlink issues on Windows**: JPM automatically falls back to directory creation.
- **Build fails**: Run ` + "`jpm build --verbose`" + ` for detailed diagnostics.

## Offline Builds

Cache dependencies locally:
` + "```bash" + `
jpm build  # Fetches and caches
jpm build --offline  # Uses cache only
` + "```" + `

Generated by JPM.
`

// Generate creates or updates README.md, optionally prompting if it already exists.
// Returns (created bool, error).
func (g *ReadmeGenerator) Generate(prompt bool) (bool, error) {
	readmePath := filepath.Join(g.projectRoot, "README.md")

	// Check if README.md exists
	_, err := os.Stat(readmePath)
	if err == nil && prompt {
		// File exists; ask user
		fmt.Println("\nREADME.md already exists.")
		fmt.Println("  1) Skip (keep existing)")
		fmt.Println("  2) Overwrite")
		fmt.Print("> ")

		var choice string
		fmt.Scanln(&choice)
		if choice != "2" {
			return false, nil // Skip
		}
	}

	// Generate content from template
	content := g.renderTemplate()

	if err := os.WriteFile(readmePath, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write README.md: %w", err)
	}

	_, existed := os.Stat(readmePath)
	return existed != nil, nil
}

// renderTemplate substitutes placeholders in the template.
func (g *ReadmeGenerator) renderTemplate() string {
	result := readmeTemplate
	result = strings.ReplaceAll(result, "{{project_name}}", g.projectName)
	result = strings.ReplaceAll(result, "{{java_version}}", g.javaVersion)
	result = strings.ReplaceAll(result, "{{tool_version}}", "0.0.354")
	return result
}
